<?php

function RbacCommandTabTable()
{
	$result = array(
		SSPACE_COMMAND_HOME,
		SSPACE_COMMAND_MY,
		SSPACE_COMMAND_RECORDER,
		SSPACE_COMMAND_CHAT,
		SSPACE_COMMAND_ADMIN,
	);

	return $result;
}

function RbacCommandMyTable()
{
	$result = array(
		SSPACE_COMMAND_MY_COURSES,
		SSPACE_COMMAND_MY_FOLDERS,
		SSPACE_COMMAND_MY_REPORTS,
		SSPACE_COMMAND_MY_RESOURCES,
		SSPACE_COMMAND_MY_FAVORITES,
		SSPACE_COMMAND_MY_INBOX,
		SSPACE_COMMAND_MY_SETTINGS,
	);

	return $result;
}

/////////////////////////////////////////////////////////////////////////

function RbacCommandObjectTable()
{
	$result = array(
		SSPACE_COMMAND_COMMENT_CREATE,
		SSPACE_COMMAND_COURSE_CREATE,
		SSPACE_COMMAND_OBJECT_CREATE_LESSON,
		SSPACE_COMMAND_OBJECT_CREATE_QUIZ,
		SSPACE_COMMAND_QUESTION_CREATE_BANK,
		SSPACE_COMMAND_OBJECT_CREATE_FLASHCARD,
		SSPACE_COMMAND_OBJECT_CREATE_SURVEY,
		SSPACE_COMMAND_OBJECT_CREATE,
		SSPACE_COMMAND_OBJECT_CREATE_POST,
		SSPACE_COMMAND_OBJECT_BROWSE,
		SSPACE_COMMAND_FILE_UPLOAD,
		SSPACE_COMMAND_FILE_RECORD,
		SSPACE_COMMAND_FILE_TEXT,
		SSPACE_COMMAND_FILE_INTERNET,
		SSPACE_COMMAND_FILE_YOUTUBE,
	//	SSPACE_COMMAND_FILE_CAPTURE,
		SSPACE_COMMAND_OBJECT_CREATE_TEXTBOOK,
		SSPACE_COMMAND_OBJECT_IMPORTFOLDER,
			
		SSPACE_COMMAND_OBJECT_RECENTS,
		SSPACE_COMMAND_SEPARATOR,
		SSPACE_COMMAND_OBJECT_COPY,
		SSPACE_COMMAND_OBJECT_CUT,
		SSPACE_COMMAND_OBJECT_PASTE,
		SSPACE_COMMAND_OBJECT_DELETE,
		SSPACE_COMMAND_OBJECT_EDIT,
	);

	return $result;
}

function RbacCommandObjectShortcut()
{
	$result = array(
		SSPACE_COMMAND_COURSE_CREATE,
		SSPACE_COMMAND_OBJECT_CREATE_LESSON,
		SSPACE_COMMAND_OBJECT_CREATE_QUIZ,
		SSPACE_COMMAND_QUESTION_CREATE_BANK,
		SSPACE_COMMAND_OBJECT_CREATE_FLASHCARD,
		SSPACE_COMMAND_OBJECT_CREATE_SURVEY,
		SSPACE_COMMAND_OBJECT_CREATE,
		SSPACE_COMMAND_OBJECT_CREATE_POST,
		SSPACE_COMMAND_OBJECT_BROWSE,
		SSPACE_COMMAND_FILE_UPLOAD,
		SSPACE_COMMAND_FILE_RECORD,
		SSPACE_COMMAND_FILE_TEXT,
		SSPACE_COMMAND_FILE_INTERNET,
		SSPACE_COMMAND_FILE_YOUTUBE,
	//	SSPACE_COMMAND_FILE_CAPTURE,
		SSPACE_COMMAND_OBJECT_EDIT,
	//	SSPACE_COMMAND_COMMENT_CREATE,
	);

	return $result;
}

/////////////////////////////////////////////////////////////////////////

function RbacCommandTextbookTable()
{
	$result = array(
		SSPACE_COMMAND_COMMENT_CREATE,
		SSPACE_COMMAND_COURSE_CREATE,
		SSPACE_COMMAND_OBJECT_CREATE_LESSON,
		SSPACE_COMMAND_OBJECT_CREATE_QUIZ,
		SSPACE_COMMAND_QUESTION_CREATE_BANK,
		SSPACE_COMMAND_OBJECT_CREATE_FLASHCARD,
		SSPACE_COMMAND_OBJECT_CREATE_SURVEY,
		SSPACE_COMMAND_OBJECT_CREATE,
		SSPACE_COMMAND_OBJECT_CREATE_POST,
		SSPACE_COMMAND_OBJECT_BROWSE,
		SSPACE_COMMAND_FILE_UPLOAD,
		SSPACE_COMMAND_FILE_RECORD,
		SSPACE_COMMAND_FILE_TEXT,
		SSPACE_COMMAND_FILE_INTERNET,
		SSPACE_COMMAND_FILE_YOUTUBE,
	//	SSPACE_COMMAND_FILE_CAPTURE,
		SSPACE_COMMAND_OBJECT_IMPORTFOLDER,

		SSPACE_COMMAND_TEXTBOOK_ACCESSCODE,
	//	SSPACE_COMMAND_TEXTBOOK_UPLOAD,
		SSPACE_COMMAND_OBJECT_RECENTS,
		SSPACE_COMMAND_SEPARATOR,
		SSPACE_COMMAND_OBJECT_COPY,
		SSPACE_COMMAND_OBJECT_CUT,
		SSPACE_COMMAND_OBJECT_PASTE,
		SSPACE_COMMAND_OBJECT_DELETE,
		SSPACE_COMMAND_OBJECT_EDIT,
	);

	return $result;
}

function RbacCommandTextbookShortcut()
{
	$result = array(
		SSPACE_COMMAND_COURSE_CREATE,
		SSPACE_COMMAND_OBJECT_CREATE_LESSON,
		SSPACE_COMMAND_OBJECT_CREATE_QUIZ,
		SSPACE_COMMAND_QUESTION_CREATE_BANK,
		SSPACE_COMMAND_OBJECT_CREATE_FLASHCARD,
		SSPACE_COMMAND_OBJECT_CREATE_SURVEY,
		SSPACE_COMMAND_OBJECT_CREATE,
		SSPACE_COMMAND_OBJECT_CREATE_POST,
		SSPACE_COMMAND_OBJECT_BROWSE,
		SSPACE_COMMAND_FILE_UPLOAD,
		SSPACE_COMMAND_FILE_RECORD,
		SSPACE_COMMAND_FILE_TEXT,
		SSPACE_COMMAND_FILE_INTERNET,
		SSPACE_COMMAND_FILE_YOUTUBE,
	//	SSPACE_COMMAND_FILE_CAPTURE,
		SSPACE_COMMAND_OBJECT_EDIT,
		SSPACE_COMMAND_TEXTBOOK_ACCESSCODE,
	//	SSPACE_COMMAND_TEXTBOOK_UPLOAD,
	);

	return $result;
}

/////////////////////////////////////////////////////////////////////////

function RbacCommandForumTable()
{
	$result = array(
		SSPACE_COMMAND_COMMENT_CREATE,

		SSPACE_COMMAND_OBJECT_CREATE_POST,
		SSPACE_COMMAND_FILE_UPLOAD,
		SSPACE_COMMAND_FILE_RECORD,

		SSPACE_COMMAND_OBJECT_RECENTS,
		SSPACE_COMMAND_SEPARATOR,
		SSPACE_COMMAND_OBJECT_COPY,
		SSPACE_COMMAND_OBJECT_CUT,
		SSPACE_COMMAND_OBJECT_PASTE,
		SSPACE_COMMAND_OBJECT_DELETE,
		SSPACE_COMMAND_OBJECT_EDIT,
	);

	return $result;
}

function RbacCommandForumShortcut()
{
	$result = array(
		SSPACE_COMMAND_OBJECT_CREATE_POST,
		SSPACE_COMMAND_FILE_UPLOAD,
		SSPACE_COMMAND_FILE_RECORD,
		SSPACE_COMMAND_OBJECT_EDIT,
	//	SSPACE_COMMAND_COMMENT_CREATE,
	);

	return $result;
}

/////////////////////////////////////////////////////////////////////////

function RbacCommandCourseTable()
{
	$result = array(
		SSPACE_COMMAND_ENROLL_ENROLL_SELF,
		SSPACE_COMMAND_ENROLL_UNENROLL_SELF,
		SSPACE_COMMAND_COMMENT_CREATE,

		SSPACE_COMMAND_OBJECT_CREATE_LESSON,
		SSPACE_COMMAND_OBJECT_CREATE_QUIZ,
		SSPACE_COMMAND_QUESTION_CREATE_BANK,
		SSPACE_COMMAND_OBJECT_CREATE_FLASHCARD,
		SSPACE_COMMAND_OBJECT_CREATE_SURVEY,
		SSPACE_COMMAND_OBJECT_CREATE,
		SSPACE_COMMAND_OBJECT_CREATE_POST,
		SSPACE_COMMAND_OBJECT_BROWSE,
		SSPACE_COMMAND_FILE_UPLOAD,
		SSPACE_COMMAND_FILE_RECORD,
		SSPACE_COMMAND_FILE_TEXT,
		SSPACE_COMMAND_FILE_INTERNET,
		SSPACE_COMMAND_FILE_YOUTUBE,
	//	SSPACE_COMMAND_FILE_CAPTURE,

		SSPACE_COMMAND_COURSE_ADDUSERS,
		SSPACE_COMMAND_COURSE_ADDROSTER,
		SSPACE_COMMAND_COURSE_REPORT_TEACHER,
		SSPACE_COMMAND_COURSE_REPORT_STUDENT,
		SSPACE_COMMAND_COURSE_RECORDINGS_TEACHER,
		SSPACE_COMMAND_COURSE_RECORDINGS_STUDENT,
				
		SSPACE_COMMAND_SEPARATOR,
		SSPACE_COMMAND_OBJECT_RECENTS,
		SSPACE_COMMAND_COURSE_CONNECT,
			
		SSPACE_COMMAND_SEPARATOR,
		SSPACE_COMMAND_OBJECT_COPY,
		SSPACE_COMMAND_OBJECT_CUT,
		SSPACE_COMMAND_OBJECT_PASTE,
		SSPACE_COMMAND_COURSE_DELETE,
		SSPACE_COMMAND_COURSE_EDITTEACHER,
		SSPACE_COMMAND_COURSE_EDIT,
	);

	return $result;
}

function RbacCommandCourseShortcut()
{
	$result = array(
		SSPACE_COMMAND_ENROLL_ENROLL_SELF,
		SSPACE_COMMAND_ENROLL_UNENROLL_SELF,
			
		SSPACE_COMMAND_OBJECT_CREATE_LESSON,
		SSPACE_COMMAND_OBJECT_CREATE_QUIZ,
		SSPACE_COMMAND_QUESTION_CREATE_BANK,
		SSPACE_COMMAND_OBJECT_CREATE_FLASHCARD,
		SSPACE_COMMAND_OBJECT_CREATE_SURVEY,
		SSPACE_COMMAND_OBJECT_CREATE,
		SSPACE_COMMAND_OBJECT_CREATE_POST,
		SSPACE_COMMAND_OBJECT_BROWSE,
		SSPACE_COMMAND_FILE_UPLOAD,
		SSPACE_COMMAND_FILE_RECORD,
		SSPACE_COMMAND_FILE_TEXT,
		SSPACE_COMMAND_FILE_INTERNET,
		SSPACE_COMMAND_FILE_YOUTUBE,
	//	SSPACE_COMMAND_FILE_CAPTURE,
			
		SSPACE_COMMAND_COURSE_ADDUSERS,
		SSPACE_COMMAND_COURSE_REPORT_TEACHER,
		SSPACE_COMMAND_COURSE_REPORT_STUDENT,
		SSPACE_COMMAND_COURSE_RECORDINGS_TEACHER,
		SSPACE_COMMAND_COURSE_RECORDINGS_STUDENT,
	//	SSPACE_COMMAND_COURSE_CONNECT,
	//	SSPACE_COMMAND_COMMENT_CREATE,
	);

	return $result;
}

/////////////////////////////////////////////////////////////////////////

function RbacCommandLessonTable()
{
	$result = array(
		SSPACE_COMMAND_ENROLL_ENROLL_SELF,
		SSPACE_COMMAND_ENROLL_UNENROLL_SELF,
		SSPACE_COMMAND_COMMENT_CREATE,

		SSPACE_COMMAND_OBJECT_CREATE_QUIZ,
		SSPACE_COMMAND_OBJECT_CREATE,
		SSPACE_COMMAND_OBJECT_CREATE_POST,
		SSPACE_COMMAND_OBJECT_BROWSE,
		SSPACE_COMMAND_FILE_UPLOAD,
		SSPACE_COMMAND_FILE_RECORD,
		SSPACE_COMMAND_FILE_TEXT,
		SSPACE_COMMAND_FILE_INTERNET,
		SSPACE_COMMAND_FILE_YOUTUBE,
	//	SSPACE_COMMAND_FILE_CAPTURE,

	//	SSPACE_COMMAND_COURSE_ADDUSERS,
		SSPACE_COMMAND_COURSE_REPORT_TEACHER,
		SSPACE_COMMAND_COURSE_REPORT_STUDENT,
		SSPACE_COMMAND_COURSE_RECORDINGS_TEACHER,
		SSPACE_COMMAND_COURSE_RECORDINGS_STUDENT,

		SSPACE_COMMAND_SEPARATOR,
		SSPACE_COMMAND_OBJECT_RECENTS,
		
		SSPACE_COMMAND_SEPARATOR,
		SSPACE_COMMAND_OBJECT_COPY,
		SSPACE_COMMAND_OBJECT_CUT,
		SSPACE_COMMAND_OBJECT_PASTE,
		SSPACE_COMMAND_OBJECT_DELETE,
		SSPACE_COMMAND_OBJECT_EDIT,
	);

	return $result;
}

function RbacCommandLessonShortcut()
{
	$result = array(
		SSPACE_COMMAND_ENROLL_ENROLL_SELF,
		SSPACE_COMMAND_ENROLL_UNENROLL_SELF,
			
		SSPACE_COMMAND_OBJECT_CREATE_QUIZ,
		SSPACE_COMMAND_OBJECT_CREATE,
		SSPACE_COMMAND_OBJECT_CREATE_POST,
		SSPACE_COMMAND_OBJECT_BROWSE,
		SSPACE_COMMAND_FILE_UPLOAD,
		SSPACE_COMMAND_FILE_RECORD,
		SSPACE_COMMAND_FILE_TEXT,
		SSPACE_COMMAND_FILE_INTERNET,
		SSPACE_COMMAND_FILE_YOUTUBE,
	//	SSPACE_COMMAND_FILE_CAPTURE,

		SSPACE_COMMAND_COURSE_REPORT_TEACHER,
		SSPACE_COMMAND_COURSE_REPORT_STUDENT,
		SSPACE_COMMAND_COURSE_RECORDINGS_TEACHER,
		SSPACE_COMMAND_COURSE_RECORDINGS_STUDENT,
	//	SSPACE_COMMAND_COMMENT_CREATE,
	);

	return $result;
}

/////////////////////////////////////////////////////////////////////////

function RbacCommandQuestionTable()
{
	$result = array(
		SSPACE_COMMAND_OBJECT_CREATE,
		SSPACE_COMMAND_OBJECT_BROWSE,
		SSPACE_COMMAND_FILE_UPLOAD,
		SSPACE_COMMAND_FILE_RECORD,
		SSPACE_COMMAND_FILE_TEXT,
		SSPACE_COMMAND_FILE_INTERNET,
		SSPACE_COMMAND_FILE_YOUTUBE,
	//	SSPACE_COMMAND_FILE_CAPTURE,
			
		SSPACE_COMMAND_QUESTION_ADMIN,
		SSPACE_COMMAND_QUESTION_CREATE,
		SSPACE_COMMAND_QUESTION_COPY_QUESTIONS,
		SSPACE_COMMAND_SEPARATOR,
		SSPACE_COMMAND_OBJECT_COPY,
		SSPACE_COMMAND_OBJECT_CUT,
		SSPACE_COMMAND_OBJECT_PASTE,
		SSPACE_COMMAND_OBJECT_DELETE,
		SSPACE_COMMAND_OBJECT_EDIT,
	);

	return $result;
}

function RbacCommandQuestionShortcut()
{
	$result = array(
		SSPACE_COMMAND_OBJECT_CREATE,
		SSPACE_COMMAND_OBJECT_BROWSE,
		SSPACE_COMMAND_FILE_UPLOAD,
		SSPACE_COMMAND_FILE_RECORD,
		SSPACE_COMMAND_FILE_TEXT,
		SSPACE_COMMAND_FILE_INTERNET,
		SSPACE_COMMAND_FILE_YOUTUBE,
	//	SSPACE_COMMAND_FILE_CAPTURE,
			
	//	SSPACE_COMMAND_OBJECT_EDIT,
		SSPACE_COMMAND_QUESTION_ADMIN,
		SSPACE_COMMAND_QUESTION_CREATE,
		SSPACE_COMMAND_QUESTION_COPY_QUESTIONS,
	);

	return $result;
}

/////////////////////////////////////////////////////////////////////////

function RbacCommandQuizTable()
{
	$result = array(
		SSPACE_COMMAND_ENROLL_ENROLL_SELF,
		SSPACE_COMMAND_ENROLL_UNENROLL_SELF,

		SSPACE_COMMAND_QUIZ_VIEW,
		SSPACE_COMMAND_QUIZ_EDIT,
		SSPACE_COMMAND_QUIZ_ADD_QUESTIONS,

	//	SSPACE_COMMAND_COURSE_ADDUSERS,
		SSPACE_COMMAND_COURSE_REPORT_TEACHER,
		SSPACE_COMMAND_COURSE_REPORT_STUDENT,
		SSPACE_COMMAND_COURSE_RECORDINGS_TEACHER,
				
		SSPACE_COMMAND_SEPARATOR,
		SSPACE_COMMAND_OBJECT_COPY,
		SSPACE_COMMAND_OBJECT_CUT,
		SSPACE_COMMAND_OBJECT_PASTE,
		SSPACE_COMMAND_OBJECT_DELETE,
		SSPACE_COMMAND_OBJECT_EDIT,
	);

	return $result;
}

function RbacCommandQuizShortcut()
{
	$result = array(
		SSPACE_COMMAND_ENROLL_ENROLL_SELF,
		SSPACE_COMMAND_ENROLL_UNENROLL_SELF,
			
		SSPACE_COMMAND_QUIZ_VIEW,
		SSPACE_COMMAND_QUIZ_EDIT,
		SSPACE_COMMAND_QUIZ_ADD_QUESTIONS,
				
		SSPACE_COMMAND_COURSE_REPORT_TEACHER,
		SSPACE_COMMAND_COURSE_REPORT_STUDENT,
		SSPACE_COMMAND_COURSE_RECORDINGS_TEACHER,
	);

	return $result;
}

/////////////////////////////////////////////////////////////////////////

function RbacCommandFlashcardTable()
{
	$result = array(
		SSPACE_COMMAND_ENROLL_ENROLL_SELF,
		SSPACE_COMMAND_ENROLL_UNENROLL_SELF,

		SSPACE_COMMAND_FLASHCARD_VIEW,
		SSPACE_COMMAND_FLASHCARD_EDIT,
				
		SSPACE_COMMAND_SEPARATOR,
		SSPACE_COMMAND_OBJECT_COPY,
		SSPACE_COMMAND_OBJECT_CUT,
		SSPACE_COMMAND_OBJECT_PASTE,
		SSPACE_COMMAND_OBJECT_DELETE,
		SSPACE_COMMAND_OBJECT_EDIT,
	);

	return $result;
}

function RbacCommandFlashcardShortcut()
{
	$result = array(
		SSPACE_COMMAND_ENROLL_ENROLL_SELF,
		SSPACE_COMMAND_ENROLL_UNENROLL_SELF,
			
		SSPACE_COMMAND_FLASHCARD_VIEW,
		SSPACE_COMMAND_FLASHCARD_EDIT,
	);

	return $result;
}

/////////////////////////////////////////////////////////////////////////

function RbacCommandSurveyTable()
{
	$result = array(
		SSPACE_COMMAND_ENROLL_ENROLL_SELF,
		SSPACE_COMMAND_ENROLL_UNENROLL_SELF,

		SSPACE_COMMAND_SURVEY_VIEW,
		SSPACE_COMMAND_SURVEY_EDIT,
		SSPACE_COMMAND_SURVEY_CREATE,
		SSPACE_COMMAND_SURVEY_RESULTS,

		SSPACE_COMMAND_COURSE_REPORT_TEACHER,
		SSPACE_COMMAND_COURSE_REPORT_STUDENT,
			
		SSPACE_COMMAND_SEPARATOR,
		SSPACE_COMMAND_OBJECT_COPY,
		SSPACE_COMMAND_OBJECT_CUT,
		SSPACE_COMMAND_OBJECT_PASTE,
		SSPACE_COMMAND_OBJECT_DELETE,
		SSPACE_COMMAND_OBJECT_EDIT,
	);

	return $result;
}

function RbacCommandSurveyShortcut()
{
	$result = array(
		SSPACE_COMMAND_ENROLL_ENROLL_SELF,
		SSPACE_COMMAND_ENROLL_UNENROLL_SELF,

		SSPACE_COMMAND_SURVEY_VIEW,
		SSPACE_COMMAND_SURVEY_EDIT,
		SSPACE_COMMAND_SURVEY_CREATE,
		SSPACE_COMMAND_SURVEY_RESULTS,

		SSPACE_COMMAND_COURSE_REPORT_TEACHER,
		SSPACE_COMMAND_COURSE_REPORT_STUDENT,
	);

	return $result;
}

/////////////////////////////////////////////////////////////////////////

function RbacCommandFileTable()
{
	$result = array(
		SSPACE_COMMAND_FILE_MODIFY,
		SSPACE_COMMAND_FILE_DOWNLOAD,
		SSPACE_COMMAND_COMMENT_CREATE,

		SSPACE_COMMAND_SEPARATOR,
		SSPACE_COMMAND_OBJECT_COPY,
		SSPACE_COMMAND_OBJECT_CUT,
		SSPACE_COMMAND_FILE_DELETE,
		SSPACE_COMMAND_FILE_EDIT,
	);

	return $result;
}

function RbacCommandFileShortcut()
{
	$result = array(
		SSPACE_COMMAND_FILE_DOWNLOAD,
		SSPACE_COMMAND_FILE_EDIT,
	//	SSPACE_COMMAND_COMMENT_CREATE,
	);

	return $result;
}

/////////////////////////////////////////////////////////////////////////

function RbacCommandLinkTable()
{
	$result = array(
		SSPACE_COMMAND_COMMENT_CREATE,

		SSPACE_COMMAND_SEPARATOR,
		SSPACE_COMMAND_OBJECT_COPY,
		SSPACE_COMMAND_OBJECT_CUT,
		SSPACE_COMMAND_OBJECT_DELETE,
		SSPACE_COMMAND_OBJECT_EDIT,
	);

	return $result;
}

function RbacCommandLinkShortcut()
{
	$result = array(
	//	SSPACE_COMMAND_COMMENT_CREATE,
	);

	return $result;
}

////////////////////////////////////////////////////////

function RbacCommandUserTableTable()
{
	$result = array(
		SSPACE_COMMAND_USER_EDIT,
		SSPACE_COMMAND_USER_FOLDER,
		SSPACE_COMMAND_USER_SESSION,
	);

	return $result;
}


////////////////////////////////////////////////////////////////////////////////////////////////

//return CHtml::listData(getdbolist('Role', "type like '%user%' order by id"), 'id', 'description');

function RbacUserRoleTable()
{
	return getdbolist('Role', "type like '%user%' order by id");
}

function RbacObjectRoleTable()
{
	return getdbolist('Role', "type like '%object%' order by id");
}

function RbacCourseRoleTable()
{
	return getdbolist('Role', "type like '%course%' order by id");
}


